### ISSUE TITLE
Network is unreachable

### ISSUE THREAD

**Issue by aminmc** [ef-labs/vertx-elasticsearch-service#4]
Hello,

I am trying to use the vertx-mod-elasticsearch with the following configuration:

In my vertx installation I've added java=com.englishtown~vertx-mod-hk2~1.6.1:com.englishtown.vertx.hk2.HK2VerticleFactory to langs.properties

container.deployModule("com.englishtown~vertx-mod-elasticsearch~1.2.0", {
  "address": "eb.elasticsearch",
    "transportAddresses": [ { "hostname": "localhost", "port": 9200 }],
    "cluster_name": "elasticsearch",
    "client_transport_sniff": true
});

I know my elastic search is running as I can see the cluster state when i hit localhost:9200.  However when I try to deploy my app.js where the elastic search module is defined i'm getting the following:

HK2 bootstrap binder class com.englishtown.vertx.hk2.BootstrapBinder was not found.  Are you missing injection bindings? 

Followed by

[Hindsight Lad] loaded [], sites [] 
[Hindsight Lad] exception caught on transport layer [[id: 0x43e06583]], closing connection 
java.net.SocketException: Network is unreachable

Any help would be appreciated

Thanks
Amin

**Comment by JavaCoreDeveloper** [comment]
Can Somebody let me know how to use elasticsearch in vertx for java. i want to write client side. i have used eventbus but i couldn't able to get it done. New to Vertx. Any help will be appreciated
